authentication-server: http://www.bjceis.com

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: ${spring.application.name}
      access-token-uri: ${authentication-server}/oauth/token
      user-authorization-uri: ${authentication-server}/oauth/authorize
    resource:
      user-info-uri: ${authentication-server}/user
    sso:
      login-path: /login

spring:
  application:
    name: workflow-designer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.33:3306/ceis_workflow?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
  resources:
    chain:
      cache: false

server:
  port: 8606

