authentication-server: http://www.bjceis.com

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: ${spring.application.name}
      access-token-uri: ${authentication-server}/oauth/token
      user-authorization-uri: ${authentication-server}/oauth/authorize
    resource:
      user-info-uri: ${authentication-server}/user

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.71.33:3306/ceis_workflow?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      initial-size: 3
      max-active: 10
      min-idle: 5
      max-wait: 5
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          enabled: true
  data:
    mongodb:
      uri: mongodb://192.168.71.34:27017/ceis_workflow
  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        naming:
        physical-strategy: com.ceis.workflow.workspace.configuration.MySQLUpperCaseStrategy
  rabbitmq:
     host: 192.168.71.32
     port: 5672
     virtual-host: /itim
     username: itim
     password: itim
     publisher-confirms: true
     publisher-returns: true
     template:
       mandatory: true
  application:
    name: workflow-workspace

server:
  port: 8605

